GET http://localhost:3000/listboletos

###
POST http://localhost:3000/create
Content-Type: application/json

{
"precio":"39.00"
}


###
DELETE http://localhost:3000/eliminarboleto/615fad85fb983d0ca5744249\


###
PUT http://localhost:3000/editarboleto/615fb589a4cee4e323e8ea8f
Content-Type: application/json

{
"precio":"3.00"
}



///Reserva 
###
GET http://localhost:3000/listReserva

###
POST http://localhost:3000/nuevaReserva
Content-Type: application/json

{
//"NVenta":"1",
"boleto":"1",
"cantidad":1,
"total":"$3.20"
//"fecha":"02/02/2021"

}

